import { PrismaClient, RoomType, PresetFrequency, PresetCategory } from '@prisma/client';

const prisma = new PrismaClient();

interface TaskPresetData {
  title: string;
  description?: string;
  icon: string;
  roomType: RoomType;
  category: PresetCategory;
  frequency: PresetFrequency;
  difficulty: number;
  estimatedMinutes: number;
  xpReward: number;
  goldReward: number;
}

const taskPresets: TaskPresetData[] = [
  // ============================================
  // KITCHEN - 25 tasks
  // ============================================
  {
    title: 'Lavar platos',
    description: 'Lavar todos los platos, vasos y utensilios sucios',
    icon: '🍽️',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'DAILY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 15,
    goldReward: 8,
  },
  {
    title: 'Limpiar encimera',
    description: 'Desinfectar y limpiar la encimera de la cocina',
    icon: '🧽',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 5,
  },
  {
    title: 'Limpiar estufa',
    description: 'Limpiar quemadores y superficie de la estufa',
    icon: '🔥',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 3,
    estimatedMinutes: 20,
    xpReward: 20,
    goldReward: 12,
  },
  {
    title: 'Limpiar microondas',
    description: 'Limpiar interior y exterior del microondas',
    icon: '📻',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 10,
    xpReward: 12,
    goldReward: 7,
  },
  {
    title: 'Limpiar refrigerador',
    description: 'Limpiar interior, repisas y organizar alimentos',
    icon: '🧊',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 3,
    estimatedMinutes: 30,
    xpReward: 25,
    goldReward: 15,
  },
  {
    title: 'Barrer piso',
    description: 'Barrer el piso de la cocina',
    icon: '🧹',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Trapear piso',
    description: 'Trapear y desinfectar el piso de la cocina',
    icon: '🪣',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 15,
    goldReward: 9,
  },
  {
    title: 'Sacar basura',
    description: 'Vaciar el bote de basura y poner bolsa nueva',
    icon: '🗑️',
    roomType: 'KITCHEN',
    category: 'GENERAL',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Organizar alacena',
    description: 'Ordenar y organizar productos en la alacena',
    icon: '📦',
    roomType: 'KITCHEN',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 30,
    xpReward: 20,
    goldReward: 12,
  },
  {
    title: 'Limpiar fregadero',
    description: 'Desinfectar y pulir el fregadero',
    icon: '🚰',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 10,
    xpReward: 12,
    goldReward: 7,
  },
  {
    title: 'Preparar desayuno',
    description: 'Preparar desayuno para la familia',
    icon: '🍳',
    roomType: 'KITCHEN',
    category: 'COOKING',
    frequency: 'DAILY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Preparar almuerzo',
    description: 'Preparar almuerzo para la familia',
    icon: '🍲',
    roomType: 'KITCHEN',
    category: 'COOKING',
    frequency: 'DAILY',
    difficulty: 3,
    estimatedMinutes: 30,
    xpReward: 20,
    goldReward: 15,
  },
  {
    title: 'Preparar cena',
    description: 'Preparar cena para la familia',
    icon: '🍽️',
    roomType: 'KITCHEN',
    category: 'COOKING',
    frequency: 'DAILY',
    difficulty: 3,
    estimatedMinutes: 30,
    xpReward: 20,
    goldReward: 15,
  },
  {
    title: 'Limpiar horno',
    description: 'Limpiar interior del horno',
    icon: '🔥',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 4,
    estimatedMinutes: 45,
    xpReward: 30,
    goldReward: 20,
  },
  {
    title: 'Lavar gabinetes',
    description: 'Limpiar exterior de gabinetes',
    icon: '🚪',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Revisar fechas de caducidad',
    description: 'Revisar alimentos caducados en despensa y refrigerador',
    icon: '📅',
    roomType: 'KITCHEN',
    category: 'ORGANIZING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Limpiar campana extractora',
    description: 'Limpiar filtros y exterior de campana',
    icon: '💨',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 3,
    estimatedMinutes: 25,
    xpReward: 20,
    goldReward: 12,
  },
  {
    title: 'Organizar refrigerador',
    description: 'Ordenar alimentos en refrigerador',
    icon: '🧊',
    roomType: 'KITCHEN',
    category: 'ORGANIZING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Limpiar lavavajillas',
    description: 'Limpiar filtros y ejecutar ciclo de limpieza',
    icon: '🧼',
    roomType: 'KITCHEN',
    category: 'MAINTENANCE',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Descongelar congelador',
    description: 'Descongelar y limpiar congelador',
    icon: '❄️',
    roomType: 'KITCHEN',
    category: 'MAINTENANCE',
    frequency: 'SEASONAL',
    difficulty: 4,
    estimatedMinutes: 60,
    xpReward: 35,
    goldReward: 25,
  },
  {
    title: 'Limpiar ventanas',
    description: 'Limpiar ventanas de la cocina',
    icon: '🪟',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Organizar cajones',
    description: 'Ordenar cajones de utensilios',
    icon: '🔪',
    roomType: 'KITCHEN',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Limpiar mesa',
    description: 'Limpiar y desinfectar mesa de cocina',
    icon: '🪑',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Reabastecer despensa',
    description: 'Hacer lista de compras y reabastecer',
    icon: '🛒',
    roomType: 'KITCHEN',
    category: 'GENERAL',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 30,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Limpiar electrodomésticos',
    description: 'Limpiar licuadora, tostador, cafetera, etc.',
    icon: '⚡',
    roomType: 'KITCHEN',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 9,
  },

  // ============================================
  // LIVING ROOM - 20 tasks
  // ============================================
  {
    title: 'Aspirar alfombras',
    description: 'Pasar aspiradora en alfombras y tapetes',
    icon: '🧹',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 15,
    goldReward: 9,
  },
  {
    title: 'Sacudir muebles',
    description: 'Quitar polvo de muebles y superficies',
    icon: '🪶',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Ordenar objetos',
    description: 'Guardar objetos en su lugar',
    icon: '📦',
    roomType: 'LIVING_ROOM',
    category: 'ORGANIZING',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 5,
  },
  {
    title: 'Limpiar TV y pantallas',
    description: 'Limpiar TV y dispositivos electrónicos',
    icon: '📺',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Lavar cojines',
    description: 'Lavar fundas de cojines',
    icon: '🛋️',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 30,
    xpReward: 20,
    goldReward: 12,
  },
  {
    title: 'Aspirar sofá',
    description: 'Aspirar sofá y sillones',
    icon: '🛋️',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Organizar libros',
    description: 'Ordenar libros en estanterías',
    icon: '📚',
    roomType: 'LIVING_ROOM',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Limpiar ventanas',
    description: 'Limpiar ventanas de la sala',
    icon: '🪟',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Barrer/trapear piso',
    description: 'Limpiar el piso de la sala',
    icon: '🧹',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Organizar cables',
    description: 'Ordenar cables de dispositivos',
    icon: '🔌',
    roomType: 'LIVING_ROOM',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Limpiar lámparas',
    description: 'Quitar polvo de lámparas y focos',
    icon: '💡',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Airear sala',
    description: 'Abrir ventanas para ventilar',
    icon: '🌬️',
    roomType: 'LIVING_ROOM',
    category: 'GENERAL',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 5,
    goldReward: 3,
  },
  {
    title: 'Limpiar espejos',
    description: 'Limpiar espejos decorativos',
    icon: '🪞',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Organizar mesa de centro',
    description: 'Ordenar objetos en mesa de centro',
    icon: '🪑',
    roomType: 'LIVING_ROOM',
    category: 'ORGANIZING',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Limpiar decoraciones',
    description: 'Quitar polvo de decoraciones',
    icon: '🎨',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 1,
    estimatedMinutes: 15,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Rotar cojines',
    description: 'Rotar y esponjar cojines del sofá',
    icon: '🔄',
    roomType: 'LIVING_ROOM',
    category: 'MAINTENANCE',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Limpiar zócalos',
    description: 'Limpiar zócalos y molduras',
    icon: '🧽',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Organizar revistas',
    description: 'Ordenar y desechar revistas viejas',
    icon: '📰',
    roomType: 'LIVING_ROOM',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Limpiar control remoto',
    description: 'Desinfectar controles remotos',
    icon: '📱',
    roomType: 'LIVING_ROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Reorganizar muebles',
    description: 'Cambiar disposición de muebles',
    icon: '🛋️',
    roomType: 'LIVING_ROOM',
    category: 'ORGANIZING',
    frequency: 'SEASONAL',
    difficulty: 4,
    estimatedMinutes: 60,
    xpReward: 30,
    goldReward: 20,
  },

  // ============================================
  // BATHROOM - 20 tasks
  // ============================================
  {
    title: 'Limpiar inodoro',
    description: 'Desinfectar y limpiar el inodoro',
    icon: '🚽',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'DAILY',
    difficulty: 2,
    estimatedMinutes: 10,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Limpiar lavabo',
    description: 'Limpiar y desinfectar el lavabo',
    icon: '🚰',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Limpiar regadera/bañera',
    description: 'Limpiar regadera, bañera y cortina',
    icon: '🚿',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 3,
    estimatedMinutes: 20,
    xpReward: 20,
    goldReward: 12,
  },
  {
    title: 'Limpiar espejo',
    description: 'Limpiar espejo del baño',
    icon: '🪞',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 5,
  },
  {
    title: 'Trapear piso',
    description: 'Trapear y desinfectar piso del baño',
    icon: '🪣',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 10,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Cambiar toallas',
    description: 'Cambiar y lavar toallas',
    icon: '🧻',
    roomType: 'BATHROOM',
    category: 'GENERAL',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Organizar gabinete',
    description: 'Ordenar productos en gabinete',
    icon: '🚪',
    roomType: 'BATHROOM',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Reabastecer papel higiénico',
    description: 'Verificar y reabastecer papel',
    icon: '🧻',
    roomType: 'BATHROOM',
    category: 'GENERAL',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Limpiar azulejos',
    description: 'Limpiar azulejos de pared',
    icon: '🧽',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Sacar basura',
    description: 'Vaciar bote de basura',
    icon: '🗑️',
    roomType: 'BATHROOM',
    category: 'GENERAL',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Limpiar grifos',
    description: 'Pulir y limpiar grifos',
    icon: '🚰',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Limpiar ventilador',
    description: 'Limpiar aspas del ventilador/extractor',
    icon: '💨',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Destapar drenajes',
    description: 'Limpiar y destapar drenajes',
    icon: '🔧',
    roomType: 'BATHROOM',
    category: 'MAINTENANCE',
    frequency: 'MONTHLY',
    difficulty: 3,
    estimatedMinutes: 20,
    xpReward: 18,
    goldReward: 12,
  },
  {
    title: 'Organizar productos',
    description: 'Ordenar productos de higiene',
    icon: '🧴',
    roomType: 'BATHROOM',
    category: 'ORGANIZING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Lavar tapetes',
    description: 'Lavar tapetes del baño',
    icon: '🧺',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Limpiar puerta',
    description: 'Limpiar puerta del baño',
    icon: '🚪',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Revisar fecha productos',
    description: 'Revisar productos caducados',
    icon: '📅',
    roomType: 'BATHROOM',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Limpiar dispensadores',
    description: 'Limpiar dispensadores de jabón',
    icon: '🧼',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Airear baño',
    description: 'Ventilar el baño',
    icon: '🌬️',
    roomType: 'BATHROOM',
    category: 'GENERAL',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 5,
    goldReward: 3,
  },
  {
    title: 'Limpiar juntas azulejos',
    description: 'Limpiar juntas entre azulejos',
    icon: '🧽',
    roomType: 'BATHROOM',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 3,
    estimatedMinutes: 30,
    xpReward: 20,
    goldReward: 15,
  },

  // ============================================
  // BEDROOM - 20 tasks
  // ============================================
  {
    title: 'Hacer cama',
    description: 'Tender y arreglar la cama',
    icon: '🛏️',
    roomType: 'BEDROOM',
    category: 'GENERAL',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Cambiar sábanas',
    description: 'Cambiar y lavar sábanas',
    icon: '🛏️',
    roomType: 'BEDROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Aspirar/barrer piso',
    description: 'Limpiar el piso de la recámara',
    icon: '🧹',
    roomType: 'BEDROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Sacudir muebles',
    description: 'Quitar polvo de muebles',
    icon: '🪶',
    roomType: 'BEDROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Organizar clóset',
    description: 'Ordenar ropa en clóset',
    icon: '👔',
    roomType: 'BEDROOM',
    category: 'ORGANIZING',
    frequency: 'WEEKLY',
    difficulty: 3,
    estimatedMinutes: 30,
    xpReward: 20,
    goldReward: 12,
  },
  {
    title: 'Guardar ropa limpia',
    description: 'Doblar y guardar ropa',
    icon: '👕',
    roomType: 'BEDROOM',
    category: 'ORGANIZING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 9,
  },
  {
    title: 'Limpiar ventanas',
    description: 'Limpiar ventanas de la recámara',
    icon: '🪟',
    roomType: 'BEDROOM',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Lavar cortinas',
    description: 'Lavar cortinas o persianas',
    icon: '🪟',
    roomType: 'BEDROOM',
    category: 'CLEANING',
    frequency: 'SEASONAL',
    difficulty: 3,
    estimatedMinutes: 30,
    xpReward: 20,
    goldReward: 15,
  },
  {
    title: 'Organizar cajones',
    description: 'Ordenar cajones del tocador',
    icon: '📦',
    roomType: 'BEDROOM',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Airear recámara',
    description: 'Ventilar la habitación',
    icon: '🌬️',
    roomType: 'BEDROOM',
    category: 'GENERAL',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 5,
    goldReward: 3,
  },
  {
    title: 'Limpiar bajo la cama',
    description: 'Limpiar y quitar polvo bajo la cama',
    icon: '🧹',
    roomType: 'BEDROOM',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Organizar buró',
    description: 'Ordenar objetos en mesita de noche',
    icon: '🛋️',
    roomType: 'BEDROOM',
    category: 'ORGANIZING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Lavar almohadas',
    description: 'Lavar almohadas y fundas',
    icon: '🛏️',
    roomType: 'BEDROOM',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Donar ropa',
    description: 'Seleccionar ropa para donar',
    icon: '👕',
    roomType: 'BEDROOM',
    category: 'ORGANIZING',
    frequency: 'SEASONAL',
    difficulty: 3,
    estimatedMinutes: 45,
    xpReward: 25,
    goldReward: 15,
  },
  {
    title: 'Limpiar lámpara',
    description: 'Quitar polvo de lámpara',
    icon: '💡',
    roomType: 'BEDROOM',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Organizar zapatos',
    description: 'Ordenar zapatos en clóset',
    icon: '👞',
    roomType: 'BEDROOM',
    category: 'ORGANIZING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Limpiar espejo',
    description: 'Limpiar espejo de la recámara',
    icon: '🪞',
    roomType: 'BEDROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Voltear colchón',
    description: 'Voltear o rotar el colchón',
    icon: '🔄',
    roomType: 'BEDROOM',
    category: 'MAINTENANCE',
    frequency: 'SEASONAL',
    difficulty: 3,
    estimatedMinutes: 20,
    xpReward: 18,
    goldReward: 12,
  },
  {
    title: 'Limpiar radiador/clima',
    description: 'Limpiar radiador o aire acondicionado',
    icon: '❄️',
    roomType: 'BEDROOM',
    category: 'MAINTENANCE',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Organizar accesorios',
    description: 'Ordenar accesorios y joyería',
    icon: '💍',
    roomType: 'BEDROOM',
    category: 'ORGANIZING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },

  // ============================================
  // LAUNDRY ROOM - 15 tasks
  // ============================================
  {
    title: 'Lavar ropa blanca',
    description: 'Lavar carga de ropa blanca',
    icon: '🤍',
    roomType: 'LAUNDRY_ROOM',
    category: 'LAUNDRY',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 60,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Lavar ropa de color',
    description: 'Lavar carga de ropa de colores',
    icon: '👕',
    roomType: 'LAUNDRY_ROOM',
    category: 'LAUNDRY',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 60,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Secar ropa',
    description: 'Tender o meter ropa a secadora',
    icon: '🌞',
    roomType: 'LAUNDRY_ROOM',
    category: 'LAUNDRY',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 15,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Doblar ropa',
    description: 'Doblar ropa seca',
    icon: '👔',
    roomType: 'LAUNDRY_ROOM',
    category: 'LAUNDRY',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 30,
    xpReward: 15,
    goldReward: 9,
  },
  {
    title: 'Planchar ropa',
    description: 'Planchar prendas necesarias',
    icon: '🔥',
    roomType: 'LAUNDRY_ROOM',
    category: 'LAUNDRY',
    frequency: 'WEEKLY',
    difficulty: 3,
    estimatedMinutes: 40,
    xpReward: 20,
    goldReward: 15,
  },
  {
    title: 'Limpiar lavadora',
    description: 'Limpiar filtro y tambor de lavadora',
    icon: '🧼',
    roomType: 'LAUNDRY_ROOM',
    category: 'MAINTENANCE',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Limpiar secadora',
    description: 'Limpiar filtro de pelusa',
    icon: '🌬️',
    roomType: 'LAUNDRY_ROOM',
    category: 'MAINTENANCE',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Organizar productos',
    description: 'Ordenar detergentes y suavizantes',
    icon: '🧴',
    roomType: 'LAUNDRY_ROOM',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Separar ropa sucia',
    description: 'Clasificar ropa por color y tipo',
    icon: '🗂️',
    roomType: 'LAUNDRY_ROOM',
    category: 'LAUNDRY',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Limpiar piso',
    description: 'Barrer y trapear cuarto de lavado',
    icon: '🧹',
    roomType: 'LAUNDRY_ROOM',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Revisar ropa dañada',
    description: 'Revisar prendas que necesitan reparación',
    icon: '🪡',
    roomType: 'LAUNDRY_ROOM',
    category: 'MAINTENANCE',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Coser botones',
    description: 'Reparar prendas sencillas',
    icon: '🪡',
    roomType: 'LAUNDRY_ROOM',
    category: 'MAINTENANCE',
    frequency: 'AS_NEEDED',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Lavar ropa delicada',
    description: 'Lavar prendas delicadas a mano',
    icon: '👗',
    roomType: 'LAUNDRY_ROOM',
    category: 'LAUNDRY',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Organizar tendedero',
    description: 'Ordenar y limpiar tendedero',
    icon: '👕',
    roomType: 'LAUNDRY_ROOM',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Reabastecer detergente',
    description: 'Comprar productos de lavandería',
    icon: '🛒',
    roomType: 'LAUNDRY_ROOM',
    category: 'GENERAL',
    frequency: 'MONTHLY',
    difficulty: 1,
    estimatedMinutes: 15,
    xpReward: 10,
    goldReward: 6,
  },

  // ============================================
  // GARAGE - 15 tasks
  // ============================================
  {
    title: 'Barrer garage',
    description: 'Barrer el piso del garage',
    icon: '🧹',
    roomType: 'GARAGE',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Organizar herramientas',
    description: 'Ordenar herramientas en su lugar',
    icon: '🔧',
    roomType: 'GARAGE',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 30,
    xpReward: 18,
    goldReward: 12,
  },
  {
    title: 'Sacar basura',
    description: 'Llevar basura a la calle',
    icon: '🗑️',
    roomType: 'GARAGE',
    category: 'GENERAL',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Limpiar coche',
    description: 'Lavar el coche',
    icon: '🚗',
    roomType: 'GARAGE',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 3,
    estimatedMinutes: 45,
    xpReward: 25,
    goldReward: 15,
  },
  {
    title: 'Aspirar coche',
    description: 'Aspirar interior del coche',
    icon: '🚙',
    roomType: 'GARAGE',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Organizar cajas',
    description: 'Ordenar cajas de almacenamiento',
    icon: '📦',
    roomType: 'GARAGE',
    category: 'ORGANIZING',
    frequency: 'SEASONAL',
    difficulty: 3,
    estimatedMinutes: 60,
    xpReward: 30,
    goldReward: 20,
  },
  {
    title: 'Revisar neumáticos',
    description: 'Verificar presión de llantas',
    icon: '⚙️',
    roomType: 'GARAGE',
    category: 'MAINTENANCE',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Limpiar estantes',
    description: 'Quitar polvo de estanterías',
    icon: '🧽',
    roomType: 'GARAGE',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Donar objetos',
    description: 'Seleccionar objetos para donar',
    icon: '📦',
    roomType: 'GARAGE',
    category: 'ORGANIZING',
    frequency: 'SEASONAL',
    difficulty: 3,
    estimatedMinutes: 45,
    xpReward: 25,
    goldReward: 15,
  },
  {
    title: 'Limpiar puerta',
    description: 'Limpiar puerta del garage',
    icon: '🚪',
    roomType: 'GARAGE',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Organizar deportes',
    description: 'Ordenar equipo deportivo',
    icon: '⚽',
    roomType: 'GARAGE',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Reciclar',
    description: 'Separar y llevar reciclaje',
    icon: '♻️',
    roomType: 'GARAGE',
    category: 'GENERAL',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Limpiar ventanas',
    description: 'Limpiar ventanas del garage',
    icon: '🪟',
    roomType: 'GARAGE',
    category: 'CLEANING',
    frequency: 'SEASONAL',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Revisar almacenamiento',
    description: 'Verificar objetos almacenados',
    icon: '📋',
    roomType: 'GARAGE',
    category: 'ORGANIZING',
    frequency: 'SEASONAL',
    difficulty: 2,
    estimatedMinutes: 30,
    xpReward: 20,
    goldReward: 12,
  },
  {
    title: 'Mantenimiento bicicletas',
    description: 'Limpiar y revisar bicicletas',
    icon: '🚴',
    roomType: 'GARAGE',
    category: 'MAINTENANCE',
    frequency: 'MONTHLY',
    difficulty: 3,
    estimatedMinutes: 30,
    xpReward: 20,
    goldReward: 15,
  },

  // ============================================
  // BACKYARD - 20 tasks
  // ============================================
  {
    title: 'Regar plantas',
    description: 'Regar todas las plantas del jardín',
    icon: '💧',
    roomType: 'BACKYARD',
    category: 'PLANTS',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 15,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Cortar césped',
    description: 'Cortar el pasto del jardín',
    icon: '🌱',
    roomType: 'BACKYARD',
    category: 'OUTDOOR',
    frequency: 'WEEKLY',
    difficulty: 3,
    estimatedMinutes: 45,
    xpReward: 25,
    goldReward: 15,
  },
  {
    title: 'Podar plantas',
    description: 'Podar arbustos y plantas',
    icon: '✂️',
    roomType: 'BACKYARD',
    category: 'PLANTS',
    frequency: 'MONTHLY',
    difficulty: 3,
    estimatedMinutes: 40,
    xpReward: 22,
    goldReward: 15,
  },
  {
    title: 'Quitar maleza',
    description: 'Eliminar hierbas no deseadas',
    icon: '🌿',
    roomType: 'BACKYARD',
    category: 'OUTDOOR',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 30,
    xpReward: 18,
    goldReward: 12,
  },
  {
    title: 'Barrer patio',
    description: 'Barrer hojas y basura del patio',
    icon: '🧹',
    roomType: 'BACKYARD',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Limpiar muebles exterior',
    description: 'Limpiar muebles de jardín',
    icon: '🪑',
    roomType: 'BACKYARD',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 25,
    xpReward: 18,
    goldReward: 12,
  },
  {
    title: 'Fertilizar plantas',
    description: 'Aplicar fertilizante a plantas',
    icon: '🌺',
    roomType: 'BACKYARD',
    category: 'PLANTS',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Limpiar parrilla',
    description: 'Limpiar asador/parrilla',
    icon: '🔥',
    roomType: 'BACKYARD',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 3,
    estimatedMinutes: 30,
    xpReward: 20,
    goldReward: 15,
  },
  {
    title: 'Revisar riego automático',
    description: 'Verificar sistema de riego',
    icon: '💧',
    roomType: 'BACKYARD',
    category: 'MAINTENANCE',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Plantar flores',
    description: 'Plantar nuevas flores de temporada',
    icon: '🌷',
    roomType: 'BACKYARD',
    category: 'PLANTS',
    frequency: 'SEASONAL',
    difficulty: 3,
    estimatedMinutes: 60,
    xpReward: 30,
    goldReward: 20,
  },
  {
    title: 'Limpiar alberca',
    description: 'Limpiar y aspirar alberca',
    icon: '🏊',
    roomType: 'BACKYARD',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 3,
    estimatedMinutes: 45,
    xpReward: 25,
    goldReward: 18,
  },
  {
    title: 'Balancear químicos alberca',
    description: 'Ajustar pH y cloro',
    icon: '🧪',
    roomType: 'BACKYARD',
    category: 'MAINTENANCE',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Limpiar caminos',
    description: 'Barrer o lavar caminos/senderos',
    icon: '🛤️',
    roomType: 'BACKYARD',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Cuidar mascotas',
    description: 'Alimentar y cuidar mascotas',
    icon: '🐕',
    roomType: 'BACKYARD',
    category: 'PETS',
    frequency: 'DAILY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Limpiar área mascotas',
    description: 'Limpiar área de mascotas',
    icon: '🐾',
    roomType: 'BACKYARD',
    category: 'PETS',
    frequency: 'DAILY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Reparar cerca',
    description: 'Revisar y reparar cercas',
    icon: '🔧',
    roomType: 'BACKYARD',
    category: 'MAINTENANCE',
    frequency: 'AS_NEEDED',
    difficulty: 4,
    estimatedMinutes: 60,
    xpReward: 30,
    goldReward: 20,
  },
  {
    title: 'Organizar bodega exterior',
    description: 'Ordenar bodega/cobertizo',
    icon: '🏠',
    roomType: 'BACKYARD',
    category: 'ORGANIZING',
    frequency: 'SEASONAL',
    difficulty: 3,
    estimatedMinutes: 45,
    xpReward: 25,
    goldReward: 15,
  },
  {
    title: 'Lavar ventanas exteriores',
    description: 'Limpiar ventanas por fuera',
    icon: '🪟',
    roomType: 'BACKYARD',
    category: 'CLEANING',
    frequency: 'SEASONAL',
    difficulty: 3,
    estimatedMinutes: 40,
    xpReward: 22,
    goldReward: 15,
  },
  {
    title: 'Preparar jardín invierno',
    description: 'Proteger plantas para invierno',
    icon: '❄️',
    roomType: 'BACKYARD',
    category: 'PLANTS',
    frequency: 'YEARLY',
    difficulty: 3,
    estimatedMinutes: 60,
    xpReward: 30,
    goldReward: 20,
  },
  {
    title: 'Decorar jardín',
    description: 'Colocar decoraciones de temporada',
    icon: '🎨',
    roomType: 'BACKYARD',
    category: 'GENERAL',
    frequency: 'SEASONAL',
    difficulty: 2,
    estimatedMinutes: 30,
    xpReward: 20,
    goldReward: 12,
  },

  // ============================================
  // HOME OFFICE - 10 tasks
  // ============================================
  {
    title: 'Organizar escritorio',
    description: 'Ordenar objetos en el escritorio',
    icon: '🖥️',
    roomType: 'HOME_OFFICE',
    category: 'ORGANIZING',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Limpiar pantallas',
    description: 'Limpiar monitores y teclado',
    icon: '⌨️',
    roomType: 'HOME_OFFICE',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Organizar cables',
    description: 'Ordenar y etiquetar cables',
    icon: '🔌',
    roomType: 'HOME_OFFICE',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Archivar documentos',
    description: 'Organizar papeles y archivos',
    icon: '📁',
    roomType: 'HOME_OFFICE',
    category: 'ORGANIZING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Vaciar papelera',
    description: 'Vaciar bote de basura',
    icon: '🗑️',
    roomType: 'HOME_OFFICE',
    category: 'GENERAL',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Limpiar librero',
    description: 'Quitar polvo de libros y estantes',
    icon: '📚',
    roomType: 'HOME_OFFICE',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Aspirar/barrer piso',
    description: 'Limpiar el piso de la oficina',
    icon: '🧹',
    roomType: 'HOME_OFFICE',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Organizar suministros',
    description: 'Ordenar materiales de oficina',
    icon: '✏️',
    roomType: 'HOME_OFFICE',
    category: 'ORGANIZING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },
  {
    title: 'Backup digital',
    description: 'Hacer respaldo de archivos',
    icon: '💾',
    roomType: 'HOME_OFFICE',
    category: 'MAINTENANCE',
    frequency: 'WEEKLY',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
  {
    title: 'Limpiar silla',
    description: 'Limpiar silla de oficina',
    icon: '🪑',
    roomType: 'HOME_OFFICE',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 15,
    xpReward: 12,
    goldReward: 8,
  },

  // ============================================
  // ENTRYWAY - 10 tasks
  // ============================================
  {
    title: 'Organizar zapatos',
    description: 'Ordenar zapatos en la entrada',
    icon: '👞',
    roomType: 'ENTRYWAY',
    category: 'ORGANIZING',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Colgar abrigos',
    description: 'Colgar abrigos y chamarras',
    icon: '🧥',
    roomType: 'ENTRYWAY',
    category: 'ORGANIZING',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Barrer entrada',
    description: 'Barrer el piso de la entrada',
    icon: '🧹',
    roomType: 'ENTRYWAY',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Limpiar espejo',
    description: 'Limpiar espejo de entrada',
    icon: '🪞',
    roomType: 'ENTRYWAY',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Sacudir tapete',
    description: 'Limpiar tapete de entrada',
    icon: '🪣',
    roomType: 'ENTRYWAY',
    category: 'CLEANING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Organizar llaves',
    description: 'Ordenar llaveros en su lugar',
    icon: '🔑',
    roomType: 'ENTRYWAY',
    category: 'ORGANIZING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Revisar correo',
    description: 'Organizar correspondencia',
    icon: '📬',
    roomType: 'ENTRYWAY',
    category: 'ORGANIZING',
    frequency: 'DAILY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Limpiar puerta',
    description: 'Limpiar puerta de entrada',
    icon: '🚪',
    roomType: 'ENTRYWAY',
    category: 'CLEANING',
    frequency: 'MONTHLY',
    difficulty: 2,
    estimatedMinutes: 10,
    xpReward: 10,
    goldReward: 6,
  },
  {
    title: 'Organizar paraguas',
    description: 'Ordenar paraguas y bastones',
    icon: '☂️',
    roomType: 'ENTRYWAY',
    category: 'ORGANIZING',
    frequency: 'WEEKLY',
    difficulty: 1,
    estimatedMinutes: 5,
    xpReward: 8,
    goldReward: 4,
  },
  {
    title: 'Decorar entrada',
    description: 'Actualizar decoración de temporada',
    icon: '🎨',
    roomType: 'ENTRYWAY',
    category: 'GENERAL',
    frequency: 'SEASONAL',
    difficulty: 2,
    estimatedMinutes: 20,
    xpReward: 15,
    goldReward: 10,
  },
];

async function main() {
  console.log('🌱 Starting task presets seed...');

  let created = 0;
  let skipped = 0;

  for (const preset of taskPresets) {
    const existing = await prisma.taskPreset.findFirst({
      where: {
        title: preset.title,
        roomType: preset.roomType,
      },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await prisma.taskPreset.create({
      data: {
        ...preset,
        isSystemPreset: true,
      },
    });
    created++;
  }

  console.log(`✅ Seed completed!`);
  console.log(`📊 Created: ${created} task presets`);
  console.log(`⏭️  Skipped: ${skipped} existing presets`);
  console.log(`📈 Total in database: ${created + skipped}`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding task presets:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
